Repository dstrigin/FoodReview, pull requests merged in 2024-12, with the labels that each got.

#16 Frontend
  .github/workflows/ci.yml
  .gitignore
  .idea/FoodReview.iml
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application.css
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/javascript/libs/stimulus-loading.js
  app/views/categories/index.html.erb
  app/views/layouts/application.html.erb
  app/views/places/index.html.erb
  bin/dev
  config/importmap.rb
  config/initializers/assets.rb
  config/routes.rb
  db/seeds.rb
  package.json
  test/fixtures/categories.yml
  test/fixtures/places.yml
  test/fixtures/types.yml
  test/system/categories_test.rb
  test/system/places_test.rb
  yarn.lock
Labels: feature, in work, test, frontend

#20 !17 Навигация
  app/controllers/home_controller.rb
  app/controllers/places_controller.rb
  app/helpers/home_helper.rb
  app/models/category.rb
  app/models/place.rb
  app/models/type.rb
  app/views/categories/index.html.erb
  app/views/home/index.html.erb
  app/views/places/index.html.erb
  app/views/places/show.html.erb
  config/routes.rb
  db/migrate/20241214203034_category_reference_in_places.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/home_controller_test.rb
  test/controllers/places_controller_test.rb
  test/system/categories_test.rb
  test/system/places_test.rb
Labels: feature, in work, frontend

#25 Просмотр заведений по категориям
  app/controllers/categories_controller.rb
  app/models/category.rb
  app/views/categories/show.html.erb
  app/views/places/show.html.erb
  db/seeds.rb
  test/controllers/categories_controller_test.rb
Labels: frontend

#18 Регистрация пользователей
  .idea/FoodReview.iml
  Gemfile
  Gemfile.lock
  Rakefile
  app/helpers/users_helper.rb
  app/javascript/application.js
  app/mailers/application_mailer.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  config/application.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/locales/devise.ru.yml
  config/routes.rb
  db/migrate/20241212133816_devise_create_users.rb
  db/migrate/20241212135559_add_confirmable_to_users.rb
  db/schema.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: feature, in work, backend, db

#28 photo
  app/assets/images/places/Keks.jpg
  app/assets/images/places/Kikchak.jpg
  app/assets/images/places/Pad_Thai.jpg
  app/helpers/application_helper.rb
  app/views/places/show.html.erb
  db/migrate/20241221092836_create_active_storage_tables.active_storage.rb
  db/migrate/20241223060014_add_pseudonym_to_places.rb
  db/migrate/20241223060900_drop_active_storage_tables.rb
  db/schema.rb
  db/seeds.rb
Labels: review
